### ISSUE TITLE
[Compatibility] vue 2.7.8

### ISSUE THREAD

**Issue by samydoesit** [geospoc/v-mapbox#1133]
Hello,
i am having a hard time upgrading this plugin.

Since v-mapbox 1.7.3 and vue 2.6.13 our markers are gone.
`TypeError: Cannot read properties of undefined (reading 'Marker')
    at a.mounted (v-mapbox.esm.js:1255:35)`

Since v-mapbox 1.11.3 and vue 2.7.8 i am getting these errors:
`TypeError: Cannot read properties of undefined (reading 'observable')
    at G (vue-composition-api.mjs:825:13)...
    
    
  v-mapbox.esm.js:1291 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'container')
    at v-mapbox.esm.js:1291:42
    `
I am not excatly sure why this happens. Can somebody help?

**Comment by vinayakkulkarni** [comment]
- [x] Ref PR: https://github.com/geospoc/v-mapbox/pull/1307
