### ISSUE TITLE
Named export 'GeolocateControl' not found - The requested module 'maplibre-gl' is a CommonJS module

### ISSUE THREAD

**Issue by 69u** [geospoc/v-mapbox#1446]
Hey there, I have tried to migrate to this module but unfortunately I have ran into a barrier and cannot get my map to initialize.

The error I get is as follows: `[Vue Router warn]: uncaught error during route navigation:                                                                                                                                   
file://node_modules/v-mapbox/dist/v-mapbox.js:1                                                                                                                                 
import { AttributionControl as E, FullscreenControl as x, GeolocateControl as A, NavigationControl as P, ScaleControl as D, Map as G, Popup as z, Marker as M } from "maplibre-gl";                   
                                                          ^^^^^^^^^^^^^^^^
SyntaxError: Named export 'GeolocateControl' not found. The requested module 'maplibre-gl' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'maplibre-gl';
const { AttributionControl: E, FullscreenControl: x, GeolocateControl: A, NavigationControl: P, ScaleControl: D, Map: G, Popup: z, Marker: M } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async ViteNodeRunner.interopedImport (file://node_modules/vite-node/dist/client.mjs:327:28)
    at async ViteNodeRunner.directRequest (file://node_modules/vite-node/dist/client.mjs:227:24)
    at async ViteNodeRunner.cachedRequest (file://node_modules/vite-node/dist/client.mjs:159:14)
    at async ViteNodeRunner.dependencyRequest (file://node_modules/vite-node/dist/client.mjs:207:14)
    at async A:\VATSAT\vatsat-cfw\components\Radar.vue:12:31
    at async ViteNodeRunner.directRequest (file://node_modules/vite-node/dist/client.mjs:315:5)`

If anyone could help me resolve this issue that would be highly appreciated :)

**Comment by stenuto** [comment]
Same here with Nuxt 3.3.3

**Comment by steklopod** [comment]
Same for nuxt

**Comment by lichstam** [comment]
any solution for this?

**Comment by Artem-Schander** [comment]
@lichstam 
until this has been fixed you could use an older version. 
I'm using v3.1.6. Be aware; the current docs are not applicable for that version.

**Comment by lalagis** [comment]
nuxt 3.5.2, same here
